services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:latest

  backend:
    depends_on:
      - mongo
      - redis
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      APP_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/webrm
      APP_REDIS_URL: redis://redis:6379
      APP_SESSION_SECRET: ${APP_SESSION_SECRET}
      APP_ALLOW_ORIGIN: ${APP_URL}:4000,${APP_URL}:5173

  frontend:
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "4000:4000"
    environment:
      VITE_APP_URL: ${APP_URL}:4000
      VITE_BACKEND_URL: ${APP_URL}:3000

volumes:
  mongo-data:
