services:
  mongo:
    image: mongo:8.0.4
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  valkey:
    image: valkey/valkey:8.0.2-alpine3.21

  backend:
    depends_on:
      - mongo
      - valkey
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      APP_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/webrm
      APP_REDIS_URL: redis://valkey:6379
      APP_SESSION_SECRET: ${WEBRM_SESSION_SECRET}
      APP_ALLOW_ORIGIN: http://localhost,${WEBRM_FRONTEND_URL}

  frontend:
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile.frontend
      args:
        WEBRM_BACKEND_URL: ${WEBRM_BACKEND_URL}
        WEBRM_FRONTEND_URL: ${WEBRM_FRONTEND_URL}
    ports:
      - "4000:4000"

volumes:
  mongo-data:
